version: "3.4"

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  camunda-client:
    # image: comerick/reaction-camunda-client:latest
    build:
      context: .
    networks:
      - reaction
    ports:
      - "8081:8081"